#!/usr/bin/env python3
"""
esttab2html.py — Convert esttab CSV (plain) output to HTML.

Usage:
    python esttab2html.py output/tables/main_table.csv
    python esttab2html.py output/tables/main_table.csv --title "Table 2: 基准回归"
    python esttab2html.py output/tables/main_table.csv --note "省份层面聚类稳健标准误"

Input:
    esttab CSV，必须带 plain 选项。

Output:
    output/tables/main_table.html — Obsidian 阅读视图预览（inline 三线表样式）
"""

import argparse
import csv
import html
import os
import re
import sys

SE_PATTERN = re.compile(r"^\(.*\)$")
SUP_PATTERN = re.compile(r"\$\^(.*?)\$")

DEFAULT_NOTE = "括号内为标准误；* p<0.10, ** p<0.05, *** p<0.01"


def die(msg):
    print(f"错误: {msg}", file=sys.stderr)
    sys.exit(1)


def parse_esttab_csv(csv_path):
    with open(csv_path, newline="", encoding="utf-8-sig") as f:
        rows = [row for row in csv.reader(f) if any(cell.strip() for cell in row)]

    if len(rows) < 2:
        die(f"CSV 内容过少（{len(rows)} 行）: {csv_path}")

    n_cols = max(len(r) for r in rows)
    rows = [r + [""] * (n_cols - len(r)) for r in rows]

    if n_cols < 2:
        die("CSV 只有一列（检查 esttab 是否加了 plain 选项）")

    if any('=""' in cell for row in rows for cell in row):
        die('检测到 ="" 包裹：esttab 缺少 plain 选项，请重新导出')

    header_rows = []
    i = 0
    while i < len(rows) and rows[i][0].strip() == "":
        header_rows.append(rows[i])
        i += 1
    if not header_rows:
        die("缺少表头行（第一行应为 depvar 名/模型编号，首列为空）")

    body = rows[i:]
    coef_rows = []
    stat_rows = []

    def followed_by_se(idx):
        return idx + 1 < len(body) and is_se_row(body[idx + 1])

    j = 0
    while j < len(body):
        row = body[j]
        if is_se_row(row):
            if coef_rows and coef_rows[-1]["se"] is None:
                coef_rows[-1]["se"] = row[1:]
            else:
                die(f"第 {j + len(header_rows) + 1} 行: SE 行没有对应的系数行")
            j += 1
            continue
        label, cells = row[0].strip(), row[1:]
        if followed_by_se(j):
            coef_rows.append({"label": label, "cells": cells, "se": body[j + 1][1:]})
            j += 2
        else:
            stat_rows.append([label] + cells)
            j += 1

    if not coef_rows and not stat_rows:
        die("未解析到任何数据行")

    return {"header_rows": header_rows, "coef_rows": coef_rows, "stat_rows": stat_rows}


def is_se_row(row):
    if row[0].strip() != "":
        return False
    values = [c.strip() for c in row[1:] if c.strip()]
    return bool(values) and all(SE_PATTERN.match(v) for v in values)


def fmt_cell(text, keep_empty=False):
    s = text.strip()
    if not s:
        return "" if keep_empty else "—"
    return SUP_PATTERN.sub(r"<sup>\1</sup>", html.escape(s))


TABLE_STYLE = (
    "border-collapse:collapse; border-top:1.5pt solid #000; "
    "border-bottom:1.5pt solid #000; font-family:SimSun,serif; font-size:10pt;"
)
TH_STYLE = "padding:2px 8px; font-weight:normal;"
TD_STYLE = "padding:2px 8px;"
SE_STYLE = "padding:2px 8px; color:#444;"


def render_html(parsed, title, note=None):
    n_cols = len(parsed["header_rows"][0])

    def cell_tag(tag, text, first, extra_style=""):
        align = "text-align:left;" if first else "text-align:center;"
        return f'<{tag} style="{align}{extra_style}">{fmt_cell(text, keep_empty=first)}</{tag}>'

    parts = []
    if title:
        parts.append(
            f'<p style="text-align:center; font-family:SimSun,serif; font-size:10.5pt;">'
            f"<strong>{html.escape(title)}</strong></p>"
        )
    parts.append(f'<table style="{TABLE_STYLE}">')

    parts.append("<thead>")
    for k, hr in enumerate(parsed["header_rows"]):
        last = k == len(parsed["header_rows"]) - 1
        style = TH_STYLE + ("border-bottom:1pt solid #000;" if last else "")
        cells = "".join(
            cell_tag("th", c, first=(idx == 0), extra_style=style)
            for idx, c in enumerate(hr)
        )
        parts.append(f"<tr>{cells}</tr>")
    parts.append("</thead>")

    parts.append("<tbody>")
    for cr in parsed["coef_rows"]:
        cells = "".join(
            cell_tag("td", c, first=(idx == 0), extra_style=TD_STYLE)
            for idx, c in enumerate([cr["label"]] + cr["cells"])
        )
        parts.append(f"<tr>{cells}</tr>")
        if cr["se"]:
            se_cells = "".join(
                cell_tag("td", c, first=(idx == 0), extra_style=SE_STYLE)
                for idx, c in enumerate([""] + cr["se"])
            )
            parts.append(f"<tr>{se_cells}</tr>")
    for sr in parsed["stat_rows"]:
        cells = "".join(
            cell_tag("td", c, first=(idx == 0), extra_style=TD_STYLE)
            for idx, c in enumerate(sr)
        )
        parts.append(f"<tr>{cells}</tr>")
    parts.append("</tbody>")
    parts.append("</table>")
    if note and note.strip():
        parts.append(
            '<p style="font-family:SimSun,serif; font-size:9pt;">'
            f"注：{html.escape(note)}。</p>"
        )
    return "<!-- Generated by esttab2html.py -->\n" + "\n".join(parts) + "\n"


def main():
    parser = argparse.ArgumentParser(
        description="Convert esttab CSV (plain) table to HTML（不依赖 pandoc）"
    )
    parser.add_argument("input", help="Path to esttab .csv file (plain)")
    parser.add_argument("--title", "-t", help="Table title")
    parser.add_argument(
        "--note", "-n",
        help=f"表尾注脚（默认: {DEFAULT_NOTE}；纯数据表如 tabstat 不传则不输出注脚）",
    )

    args = parser.parse_args()

    csv_path = args.input
    if not os.path.exists(csv_path):
        die(f"找不到文件 {csv_path}")
    if not csv_path.lower().endswith(".csv"):
        die(f"输入必须是 esttab CSV 文件（plain 格式）: {csv_path}")

    parsed = parse_esttab_csv(csv_path)

    html_path = os.path.splitext(csv_path)[0] + ".html"

    note = DEFAULT_NOTE if parsed["coef_rows"] else None
    if note and args.note:
        note = f"{note}；{args.note}"
    elif args.note:
        note = args.note

    with open(html_path, "w", encoding="utf-8") as f:
        f.write(render_html(parsed, args.title, note=note))
    print(f"✅ {html_path}")


if __name__ == "__main__":
    main()
